/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14-20250430120000+0000/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id ("org.jetbrains.kotlin.jvm") version "2.0.21"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

group = "org.debian.gradle"
version = "1.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(gradleApi())
    implementation("org.openrewrite:rewrite-gradle:8.59.1")
    implementation("org.yaml:snakeyaml:2.2")
    implementation("org.openrewrite:rewrite-gradle:8.59.1")
    implementation("org.openrewrite:rewrite-kotlin:8.59.1")
}
